#!/bin/bash

clear
failed=0

chmod 777 ./
chmod 777 web
ldd etracker | grep "=> /" | awk '{print $3}' | xargs -I '{}' cp -v --parents '{}' ./
ldd etracker | grep -e "^\s*/" | awk '{print $1}' | xargs -I '{}' cp -v --parents '{}' ./

# Почему-то эта библиотека не видна через ldd, она нужна для getpwnam
cp --parents /lib/x86_64-linux-gnu/libnss_compat.so.2 ./
cp --parents /etc/passwd ./

# Для getloadavg
mkdir proc
mount -r -t proc proc proc/

# Для sysconf(_SC_NPROCESSORS_ONLN)
mkdir sys
mount -r -t sysfs sys sys/

while true; do
  date
  chroot ./ /etracker -p $1 -i 239 -e 300 -k --nofile 64000 --core -1 --charset utf-8 --locale en_US.UTF-8 -f $failed
  echo Exit code: $?
  ((failed=failed+1))
  sleep 1
done

umount proc/
umount sys/
